module.exports = {
  // 有效成绩
  scores: [
    {
      termName: "2022-2023学年第一学期",
      scoreList: [
        {
          num: "B1011003",
          name: "军事训练",
          courseCredit: "2.0",
          category: "其他",
          courseCategory: "",
          method: "考查",
          property: "初修",
          score: "86.00",
          credit: "2.0",
          GP: "3.6",
          GPA: "7.20",
          mark: "",
        },
        {
          num: "B0914005",
          name: "大学体育1",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "体育专项类",
          method: "非统考",
          property: "初修",
          score: "78.00",
          credit: "1.0",
          GP: "2.8",
          GPA: "2.80",
          mark: "",
        },
        {
          num: "U0703001",
          name: "大学英语1",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "统考",
          property: "初修",
          score: "90.00",
          credit: "3.0",
          GP: "4.0",
          GPA: "12.00",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      scoreList: [
        {
          num: "U0202118",
          name: "网站综合设计",
          courseCredit: "2.0",
          category: "技能训练",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "95.00",
          credit: "2.0",
          GP: "4.5",
          GPA: "9.0",
          mark: "",
        },
        {
          num: "U0703002",
          name: "大学英语2",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "95.00",
          credit: "3.0",
          GP: "4.5",
          GPA: "13.50",
          mark: "",
        },
        {
          num: "U0901002",
          name: "大学体育2",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "88.00",
          credit: "1.0",
          GP: "3.8",
          GPA: "3.80",
          mark: "",
        },
      ],
    },
  ],
  // 原始成绩
  rawScores: [
    {
      termName: "2022-2023学年第一学期",
      scoreList: [
        {
          num: "U1002001",
          name: "军事训练",
          courseCredit: "2.0",
          category: "军训",
          courseCategory: "",
          method: "",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "86.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "B0914005",
          name: "大学体育1",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "体育专项类",
          method: "非统考",
          property: "初修",
          normalScore: "76.00",
          midtermScore: "",
          finalScore: "80.00",
          skillScore: "",
          complexScore: "78.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "U0703001",
          name: "大学英语1",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "统考",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "90.00",
          minorMark: "主修",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      scoreList: [
        {
          num: "P0604008",
          name: "网页视觉设计",
          courseCredit: "1.0",
          category: "公共课/公选课",
          courseCategory: "人文与艺术类",
          method: "考查",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "95.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "U0703002",
          name: "大学英语2",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "95.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "U0901002",
          name: "大学体育2",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          normalScore: "90.00",
          midtermScore: "",
          finalScore: "80.00",
          skillScore: "",
          complexScore: "88.00",
          minorMark: "主修",
          mark: "",
        },
      ],
    },
  ],
  // 考勤
  attendances: [
    {
      termName: "2022-2023学年第一学期",
      attendanceList: [
        {
          teacher: "黄老师",
          teacherNum: "200202010",
          classroom: "270777-018",
          week: "08",
          section: "三(03节)",
          date: "2022-11-10",
          reason: "请假",
          mark: "",
        },
        {
          teacher: "黄老师",
          teacherNum: "200202010",
          classroom: "270777-018",
          week: "08",
          section: "三(04节)",
          date: "2022-11-10",
          reason: "请假",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      attendanceList: [
        {
          teacher: "江老师",
          teacherNum: "200202009",
          classroom: "270777-018",
          week: "04",
          section: "三(03节)",
          date: "2023-03-10",
          reason: "旷课",
          mark: "",
        },
        {
          teacher: "江老师",
          teacherNum: "200202009",
          classroom: "270777-018",
          week: "04",
          section: "三(04节)",
          date: "2023-03-10",
          reason: "旷课",
          mark: "",
        },
      ],
    },
  ],
  // 课表
  courses: [
    {
      name: "思想政治实践课1",
      num: "U1300007",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "通识教育课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "猫猫老师",
      weeks: [1, 3, 5, 7, 9, 11, 13, 15, 17],
      section: "9",
      address: "",
      rawWeeks: "1-18",
      rawSection: "二[9-10节]单",
      week: 2,
      sectionCount: 2,
    },
    {
      name: "创新设计与创业基础",
      num: "U0602406",
      credit: "2.0",
      totalHours: "32.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "通识教育课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "小熊老师",
      weeks: [1, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
      section: 3,
      address: "创新楼403",
      rawWeeks: "1-6,8-19",
      rawSection: "三[3-4节]",
      week: 3,
      sectionCount: 2,
    },
    {
      name: "财务会计1",
      num: "U0403008",
      credit: "3.0",
      totalHours: "54.0",
      lectureHours: "54.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "小明老师",
      weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17],
      section: 1,
      address: "博士楼502",
      rawWeeks: "1-10,12-17",
      rawSection: "一[1-2节]",
      week: 1,
      sectionCount: 2,
    },
    {
      name: "财务会计1",
      credit: "3.0",
      totalHours: "54.0",
      lectureHours: "54.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "小明老师",
      weeks: [1, 2, 3, 5, 7, 9, 11, 13, 15, 17, 19],
      section: 3,
      address: "博士楼502",
      rawWeeks: "1-17,19",
      rawSection: "四[3-4节]单",
      week: 4,
      sectionCount: 2,
    },
    {
      name: "小程序开发从入门到放弃",
      num: "U0402043",
      credit: "2.0",
      totalHours: "34.0",
      lectureHours: "34.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "蛋白熙",
      weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
      section: 5,
      address: "B站BV1go4y1M7Fa",
      rawWeeks: "1-18",
      rawSection: "四[5-8节]",
      week: 1,
      sectionCount: 4,
    },
    {
      name: "大学英语A2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "通识教育课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "小美",
      weeks: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
      section: 1,
      address: "勤奋楼203",
      rawWeeks: "2-18",
      rawSection: "五[1-2节]",
      week: 5,
      sectionCount: 2,
    },
    {
      name: "大学体育2",
      num: "U0901002",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "通识教育课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "小帅",
      weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
      section: 5,
      address: "田径场",
      rawWeeks: "1-18",
      rawSection: "二[5-6节]",
      week: 2,
      sectionCount: 2,
    },
    {
      name: "高等数学A2",
      num: "U0903011",
      credit: "3.0",
      totalHours: "48.0",
      lectureHours: "48.0",
      computeHours: "0.0",
      category: "通识教育课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "小新",
      weeks: [1, 2, 3, 4, 5, 6, 8, 9, 11, 12, 13, 14, 15, 16, 17, 19, 20],
      section: 1,
      address: "宏远楼410",
      rawWeeks: "1-6,8-9,11-17,19-20",
      rawSection: "二[1-2节]",
      week: 2,
      sectionCount: 2,
    },
    {
      name: "高等数学A2",
      credit: "3.0",
      totalHours: "48.0",
      lectureHours: "48.0",
      computeHours: "0.0",
      category: "通识教育课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "小新",
      weeks: [3, 4, 5, 8, 9],
      section: 3,
      address: "功德楼602",
      rawWeeks: "3-5,8-9",
      rawSection: "五[5-6节]",
      week: 5,
      sectionCount: 2,
    },
    {
      name: "中国近现代史纲要",
      credit: "2.0",
      totalHours: "32.0",
      lectureHours: "32.0",
      computeHours: "0.0",
      category: "通识教育课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "小玲",
      weeks: [1, 3, 5, 7, 9, 11],
      section: 11,
      address: "梅勇楼401",
      rawWeeks: "1-11",
      rawSection: "四[11节]单",
      week: 4,
      sectionCount: 1,
    },
  ],
}
