module.exports = {
  // 有效成绩
  scores: [
    {
      termName: "2022-2023学年第一学期",
      scoreList: [
        {
          name: "[B1011003]军事训练",
          courseCredit: "2.0",
          category: "其他",
          courseCategory: "",
          method: "考查",
          property: "初修",
          score: "86.00",
          credit: "2.0",
          GP: "3.6",
          GPA: "7.20",
          mark: "",
        },
        {
          name: "[B0914005]大学体育1",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "体育专项类",
          method: "非统考",
          property: "初修",
          score: "78.00",
          credit: "1.0",
          GP: "2.8",
          GPA: "2.80",
          mark: "",
        },
        {
          name: "[U0703001]大学英语1",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "统考",
          property: "初修",
          score: "90.00",
          credit: "3.0",
          GP: "4.0",
          GPA: "12.00",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      scoreList: [
        {
          name: "[U0202118]网站综合设计",
          courseCredit: "2.0",
          category: "技能训练",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "95.00",
          credit: "2.0",
          GP: "4.5",
          GPA: "9.0",
          mark: "",
        },
        {
          name: "[U0703002]大学英语2",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "95.00",
          credit: "3.0",
          GP: "4.5",
          GPA: "13.50",
          mark: "",
        },
        {
          name: "[U0901002]大学体育2",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "88.00",
          credit: "1.0",
          GP: "3.8",
          GPA: "3.80",
          mark: "",
        },
      ],
    },
  ],
  // 原始成绩
  rawScores: [
    {
      termName: "2022-2023学年第一学期",
      scoreList: [
        {
          name: "[U1002001]军事训练",
          courseCredit: "2.0",
          category: "军训",
          courseCategory: "",
          method: "",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "86.00",
          minorMark: "主修",
          mark: "",
        },
        {
          name: "[B0914005]大学体育1",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "体育专项类",
          method: "非统考",
          property: "初修",
          normalScore: "76.00",
          midtermScore: "",
          finalScore: "80.00",
          skillScore: "",
          complexScore: "78.00",
          minorMark: "主修",
          mark: "",
        },
        {
          name: "[U0703001]大学英语1",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "统考",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "90.00",
          minorMark: "主修",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      scoreList: [
        {
          name: "[P0604008]网页视觉设计",
          courseCredit: "1.0",
          category: "公共课/公选课",
          courseCategory: "人文与艺术类",
          method: "考查",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "95.00",
          minorMark: "主修",
          mark: "",
        },
        {
          name: "[U0703002]大学英语2",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "95.00",
          minorMark: "主修",
          mark: "",
        },
        {
          name: "[U0901002]大学体育2",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          normalScore: "90.00",
          midtermScore: "",
          finalScore: "80.00",
          skillScore: "",
          complexScore: "88.00",
          minorMark: "主修",
          mark: "",
        },
      ],
    },
  ],
}
