module.exports = {
  // 有效成绩
  scores: [
    {
      termName: "2022-2023学年第一学期",
      scoreList: [
        {
          num: "B1011003",
          name: "军事训练",
          courseCredit: "2.0",
          category: "其他",
          courseCategory: "",
          method: "考查",
          property: "初修",
          score: "86.00",
          credit: "2.0",
          GP: "3.6",
          GPA: "7.20",
          mark: "",
        },
        {
          num: "B0914005",
          name: "大学体育1",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "体育专项类",
          method: "非统考",
          property: "初修",
          score: "78.00",
          credit: "1.0",
          GP: "2.8",
          GPA: "2.80",
          mark: "",
        },
        {
          num: "U0703001",
          name: "大学英语1",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "统考",
          property: "初修",
          score: "90.00",
          credit: "3.0",
          GP: "4.0",
          GPA: "12.00",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      scoreList: [
        {
          num: "U0202118",
          name: "网站综合设计",
          courseCredit: "2.0",
          category: "技能训练",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "95.00",
          credit: "2.0",
          GP: "4.5",
          GPA: "9.0",
          mark: "",
        },
        {
          num: "U0703002",
          name: "大学英语2",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "95.00",
          credit: "3.0",
          GP: "4.5",
          GPA: "13.50",
          mark: "",
        },
        {
          num: "U0901002",
          name: "大学体育2",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          score: "88.00",
          credit: "1.0",
          GP: "3.8",
          GPA: "3.80",
          mark: "",
        },
      ],
    },
  ],
  // 原始成绩
  rawScores: [
    {
      termName: "2022-2023学年第一学期",
      scoreList: [
        {
          num: "U1002001",
          name: "军事训练",
          courseCredit: "2.0",
          category: "军训",
          courseCategory: "",
          method: "",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "86.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "B0914005",
          name: "大学体育1",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "体育专项类",
          method: "非统考",
          property: "初修",
          normalScore: "76.00",
          midtermScore: "",
          finalScore: "80.00",
          skillScore: "",
          complexScore: "78.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "U0703001",
          name: "大学英语1",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "统考",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "90.00",
          minorMark: "主修",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      scoreList: [
        {
          num: "P0604008",
          name: "网页视觉设计",
          courseCredit: "1.0",
          category: "公共课/公选课",
          courseCategory: "人文与艺术类",
          method: "考查",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "95.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "U0703002",
          name: "大学英语2",
          courseCredit: "3.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          normalScore: "",
          midtermScore: "",
          finalScore: "",
          skillScore: "",
          complexScore: "95.00",
          minorMark: "主修",
          mark: "",
        },
        {
          num: "U0901002",
          name: "大学体育2",
          courseCredit: "1.0",
          category: "公共课/必修课",
          courseCategory: "",
          method: "非统考",
          property: "初修",
          normalScore: "90.00",
          midtermScore: "",
          finalScore: "80.00",
          skillScore: "",
          complexScore: "88.00",
          minorMark: "主修",
          mark: "",
        },
      ],
    },
  ],
  // 考勤
  attendances: [
    {
      termName: "2022-2023学年第一学期",
      attendanceList: [
        {
          teacher: "黄老师",
          teacherNum: "200202010",
          classroom: "270777-018",
          week: "08",
          section: "三(03节)",
          date: "2022-11-10",
          reason: "请假",
          mark: "",
        },
        {
          teacher: "黄老师",
          teacherNum: "200202010",
          classroom: "270777-018",
          week: "08",
          section: "三(04节)",
          date: "2022-11-10",
          reason: "请假",
          mark: "",
        },
      ],
    },
    {
      termName: "2022-2023学年第二学期",
      attendanceList: [
        {
          teacher: "江老师",
          teacherNum: "200202009",
          classroom: "270777-018",
          week: "04",
          section: "三(03节)",
          date: "2023-03-10",
          reason: "旷课",
          mark: "",
        },
        {
          teacher: "江老师",
          teacherNum: "200202009",
          classroom: "270777-018",
          week: "04",
          section: "三(04节)",
          date: "2023-03-10",
          reason: "旷课",
          mark: "",
        },
      ],
    },
  ],
  // 课表
  courses: [
    {
      name: "电子工艺实习A",
      num: "J0201048",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "夏老师",
      week: "6",
      section: "一[1-4节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "郑老师",
      week: "6",
      section: "一[1-4节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "夏老师",
      week: "6",
      section: "二[1-4节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "郑老师",
      week: "6",
      section: "二[1-4节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "夏老师",
      week: "6",
      section: "三[5-8节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "郑老师",
      week: "6",
      section: "三[5-8节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "夏老师",
      week: "6",
      section: "五[1-4节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "郑老师",
      week: "6",
      section: "五[1-4节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "夏老师",
      week: "6",
      section: "五[5-8节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "电子工艺实习A",
      credit: "1.0",
      totalHours: "20.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "郑老师",
      week: "6",
      section: "五[5-8节]",
      address: "躬行楼_402_电子线路综合实验室",
    },
    {
      name: "人工智能编程实践",
      num: "J0202207",
      credit: "2.0",
      totalHours: "40.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "马老师",
      week: "12",
      section: "一[9-12节]",
      address: "躬行楼_610_信息处理综合实验室",
    },
    {
      name: "人工智能编程实践",
      credit: "2.0",
      totalHours: "40.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "马老师",
      week: "11-12",
      section: "二[1-4节]",
      address: "躬行楼_610_信息处理综合实验室",
    },
    {
      name: "人工智能编程实践",
      credit: "2.0",
      totalHours: "40.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "马老师",
      week: "11-12",
      section: "二[9-12节]",
      address: "躬行楼_610_信息处理综合实验室",
    },
    {
      name: "人工智能编程实践",
      credit: "2.0",
      totalHours: "40.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "马老师",
      week: "11",
      section: "三[5-8节]",
      address: "躬行楼_610_信息处理综合实验室",
    },
    {
      name: "人工智能编程实践",
      credit: "2.0",
      totalHours: "40.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "马老师",
      week: "11-12",
      section: "四[9-12节]",
      address: "躬行楼_610_信息处理综合实验室",
    },
    {
      name: "人工智能编程实践",
      credit: "2.0",
      totalHours: "40.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "实验",
      method: "非统考",
      teacher: "马老师",
      week: "11-12",
      section: "五[1-4节]",
      address: "躬行楼_610_信息处理综合实验室",
    },
    {
      name: "思想政治实践课1",
      num: "U1300007",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "0.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "梁老师",
      week: "3-18",
      section: "五[11-12节]单",
      address: "",
    },
    {
      name: "物理与艺术",
      num: "P0205002",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "公共课/任选课",
      teachMethod: "网络授课",
      method: "考查",
      teacher: "杨老师",
      week: "4-11",
      section: "一[7-8节]",
      address: "",
    },
    {
      name: "人工智能数学基础",
      num: "U0203160",
      credit: "3.0",
      totalHours: "48.0",
      lectureHours: "24.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "张老师",
      week: "3-5,7-10,13-17",
      section: "二[1-2节]",
      address: "至善楼_501_4类多媒体",
    },
    {
      name: "人工智能数学基础",
      credit: "3.0",
      totalHours: "48.0",
      lectureHours: "24.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "张老师",
      week: "3,8-11,14-20",
      section: "三[3-4节]",
      address: "躬行楼_508_组态控制室",
    },
    {
      name: "大学英语B2",
      num: "U0704080",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "吴老师",
      week: "7,9,13,15",
      section: "一[5-6节]",
      address: "思齐楼_205_多媒体教室",
    },
    {
      name: "大学英语B2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "吴老师",
      week: "3-4",
      section: "二[3-4节]",
      address: "思齐楼_602_4类多媒体",
    },
    {
      name: "大学英语B2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "吴老师",
      week: "5,7-10,13-19",
      section: "二[3-4节]",
      address: "思齐楼_211_语音室（10）",
    },
    {
      name: "大学英语B2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "吴老师",
      week: "3-5,7-10,13-19",
      section: "五[1-2节]",
      address: "思齐楼_211_语音室（10）",
    },
    {
      name: "数学建模",
      num: "P0905007",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "公共课/任选课",
      teachMethod: "讲授",
      method: "考查",
      teacher: "周老师",
      week: "13-19",
      section: "一[7-8节]",
      address: "思齐楼_404_1类多媒体",
    },
    {
      name: "数学建模",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "公共课/任选课",
      teachMethod: "讲授",
      method: "考查",
      teacher: "周老师",
      week: "20",
      section: "一[7-8节]",
      address: "思齐楼_404_1类多媒体",
    },
    {
      name: "大学体育2",
      num: "U0901002",
      credit: "1.0",
      totalHours: "36.0",
      lectureHours: "36.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "江老师",
      week: "3-17,19",
      section: "四[3-4节]",
      address: "操场",
    },
    {
      name: "高等数学2",
      num: "U0904016",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "刘老师",
      week: "3-5,7-10,13-20",
      section: "一[3-4节]",
      address: "思齐楼_409_1类多媒体",
    },
    {
      name: "高等数学2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "刘老师",
      week: "14-15",
      section: "二[5-6节]",
      address: "思齐楼_402_4类多媒体",
    },
    {
      name: "高等数学2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "刘老师",
      week: "3-4",
      section: "二[5-6节]",
      address: "思齐楼_202_4类多媒体",
    },
    {
      name: "高等数学2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "刘老师",
      week: "5,7-10,13",
      section: "二[5-6节]",
      address: "思齐楼_409_1类多媒体",
    },
    {
      name: "高等数学2",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "64.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "刘老师",
      week: "14-20",
      section: "三[7-8节]",
      address: "思齐楼_403_4类多媒体",
    },
    {
      name: "大学物理A",
      num: "U0904018",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "14,16",
      section: "一[5-6节]",
      address: "至善楼_301_多媒体教室",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "10",
      section: "三[5-8节]",
      address: "躬行楼_509_大学物理实验室1",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "3-5,8,12-20",
      section: "三[5-6节]",
      address: "至善楼_305_多媒体教室",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "3-5,7-8,13-20",
      section: "四[1-2节]单",
      address: "至善楼_402_4类多媒体",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "12",
      section: "四[5-8节]",
      address: "躬行楼_509_大学物理实验室1",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "8",
      section: "四[9-12节]",
      address: "躬行楼_511_大学物理实验室2",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "9",
      section: "四[9-12节]",
      address: "躬行楼_509_大学物理实验室1",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "3-4",
      section: "五[5-6节]",
      address: "至善楼_304_1类多媒体",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "8",
      section: "五[5-8节]",
      address: "躬行楼_511_大学物理实验室2",
    },
    {
      name: "大学物理A",
      credit: "4.0",
      totalHours: "64.0",
      lectureHours: "44.0",
      computeHours: "0.0",
      category: "专业课/必修课",
      teachMethod: "讲授",
      method: "统考",
      teacher: "杨老师",
      week: "9,10,12",
      section: "五[5-8节]",
      address: "躬行楼_509_大学物理实验室1",
    },
    {
      name: "中国近现代史纲要",
      num: "U1302012",
      credit: "2.0",
      totalHours: "32.0",
      lectureHours: "32.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "梁老师",
      week: "7",
      section: "一[1-2节]",
      address: "至善楼_309_1类多媒体",
    },
    {
      name: "中国近现代史纲要",
      credit: "2.0",
      totalHours: "32.0",
      lectureHours: "32.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "梁老师",
      week: "3-12,15",
      section: "一[5-6节]双",
      address: "至善楼_309_1类多媒体",
    },
    {
      name: "中国近现代史纲要",
      credit: "2.0",
      totalHours: "32.0",
      lectureHours: "32.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "梁老师",
      week: "3-6,8-12,15",
      section: "三[1-2节]",
      address: "至善楼_509_1类多媒体",
    },
    {
      name: "形势与政策2",
      num: "U1300020",
      credit: "0.4",
      totalHours: "8.0",
      lectureHours: "6.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "李老师",
      week: "13-15",
      section: "五[5-6节]",
      address: "至善楼_511_1类多媒体",
    },
    {
      name: "军事理论",
      num: "U1302015",
      credit: "2.0",
      totalHours: "32.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "黄老师",
      week: "3-17",
      section: "四[1-2节]双",
      address: "至善楼_410_1类多媒体",
    },
    {
      name: "军事理论",
      credit: "2.0",
      totalHours: "32.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "黄老师",
      week: "18",
      section: "五[7-8节]双",
      address: "至善楼_510_1类多媒体",
    },
    {
      name: "“四史”教育",
      num: "U1301021",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "梁老师",
      week: "16-20",
      section: "二[5-6节]",
      address: "至善楼_509_1类多媒体",
    },
    {
      name: "“四史”教育",
      credit: "1.0",
      totalHours: "16.0",
      lectureHours: "16.0",
      computeHours: "0.0",
      category: "公共课/必修课",
      teachMethod: "讲授",
      method: "非统考",
      teacher: "梁老师",
      week: "16-20",
      section: "三[1-2节]双",
      address: "至善楼_509_1类多媒体",
    },
  ],
}
